// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDn0CT7k3KqJRoYwJiZBmBCkPISQmmJp8',
    appId: '1:322654127219:web:2fdf17acbd89a7759a9606',
    messagingSenderId: '322654127219',
    projectId: 'novel-flutter-4b1cf',
    authDomain: 'novel-flutter-4b1cf.firebaseapp.com',
    storageBucket: 'novel-flutter-4b1cf.firebasestorage.app',
    measurementId: 'G-ZZEQJFWW4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzY204cOGnEqzZLtPAsE54KFATch-2W1A',
    appId: '1:322654127219:android:2ca0c27d5f4e091c9a9606',
    messagingSenderId: '322654127219',
    projectId: 'novel-flutter-4b1cf',
    storageBucket: 'novel-flutter-4b1cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEPN_8zhfBmdLsB3_Cro1y5ange9xEGU',
    appId: '1:322654127219:ios:19be8d62cd401b849a9606',
    messagingSenderId: '322654127219',
    projectId: 'novel-flutter-4b1cf',
    storageBucket: 'novel-flutter-4b1cf.firebasestorage.app',
    iosBundleId: 'com.example.buatCerita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGYuAGVtoY2WJVYyGFkpvWtO9x--OYDjI',
    appId: '1:161223041926:ios:2640f496f09fee6c8e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    storageBucket: 'apk-novel.firebasestorage.app',
    iosBundleId: 'com.example.buatCeritaFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFG_5S5q92llJOXsrNmsZ8EDcfdsXOLQA',
    appId: '1:161223041926:web:8746c7153fe64d778e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    authDomain: 'apk-novel.firebaseapp.com',
    storageBucket: 'apk-novel.firebasestorage.app',
    measurementId: 'G-GXWH2W2MW4',
  );

}