// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFG_5S5q92llJOXsrNmsZ8EDcfdsXOLQA',
    appId: '1:161223041926:web:f5bb12f4f5aee5b28e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    authDomain: 'apk-novel.firebaseapp.com',
    storageBucket: 'apk-novel.firebasestorage.app',
    measurementId: 'G-1LZN260QK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeT6PnUwP7ciYGmxH554yvanDlxtI5DY',
    appId: '1:161223041926:android:c6cbfeafacdc32eb8e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    storageBucket: 'apk-novel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGYuAGVtoY2WJVYyGFkpvWtO9x--OYDjI',
    appId: '1:161223041926:ios:2640f496f09fee6c8e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    storageBucket: 'apk-novel.firebasestorage.app',
    iosBundleId: 'com.example.buatCeritaFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGYuAGVtoY2WJVYyGFkpvWtO9x--OYDjI',
    appId: '1:161223041926:ios:2640f496f09fee6c8e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    storageBucket: 'apk-novel.firebasestorage.app',
    iosBundleId: 'com.example.buatCeritaFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFG_5S5q92llJOXsrNmsZ8EDcfdsXOLQA',
    appId: '1:161223041926:web:8746c7153fe64d778e4207',
    messagingSenderId: '161223041926',
    projectId: 'apk-novel',
    authDomain: 'apk-novel.firebaseapp.com',
    storageBucket: 'apk-novel.firebasestorage.app',
    measurementId: 'G-GXWH2W2MW4',
  );

}